### ISSUE TITLE
Documentation needs updates

### ISSUE THREAD

**Issue by nwolek** [nwolek/vbap#1]
@bltzr @jln-

I am contacting you because I seem to remember one or both of you having use Ville Pullki’s VBAP external during our work on Jamoma. Someone recently contacted me after seeing my 64-bit update of the old externals. They wanted a Windows build, so I contacted Ville and got permission to set up this repository.

Everything compiles for both platforms now. The trouble is that the documentation is original and untouched. I personally don’t have much experience with the externals. Ville is too busy to update the documentation. Without some updates, it is of limited use for new people who are unfamiliar with the external.

Would either of you have time and interest in helping with this? No deadline really. I just would rather finish this off into a usable package.

**Comment by nwolek** [comment]
@pierreguillot 

I see that you have a similar repo where you are maintaining build for PD. Would you be interested in helping with the documentation here too? Or do the PD v Max versions differ significantly?

**Comment by pierreguillot** [comment]
@nwolek 
Sorry, this is my personal implementation of the VBAP, there are very few in common with the one of Ville Pulkki and I don't use its original code at all.

**Comment by nwolek** [comment]
@pierreguillot 

Thanks for the reply. I received an email from @jln- today and it sounds like he is interested in helping with this. Hopefully we can pull something together. Take care.

**Comment by sone** [comment]
@nwolek
Do you still need help with the documentation? I would gladly contribute something.

**Comment by nwolek** [comment]
@sone 
We would certainly welcome your help! @jln- did some work over the weekend, and he was emailing with me about it. He would have to respond about the specifics of where things stand currently.

**Comment by jln-** [comment]
I just sent a pull request to merge documentation update I did on my repository fork.

As it is, I did a refpage (where a few obscure messages could be better explained) and a maxhelp.

All content should be more or less here but suggestions are welcome. Let me know what you think of it !

**Comment by nwolek** [comment]
@jln- That makes things so much clearer! I can actually see how to use this now. Thank you!!!

My biggest issue now is that the help patches are too tall for my laptop screen (MacBook Pro Retina, Mid 2012). I can handle adjustments to that. 

In addition, the information from the XML file is not being read here by the JSUI or the reference panel. Let me investigate that.

I noticed you left the define_loudspeakers external out of your documentation. There is a significant overlap in the code, so I see why people likely don't use it much. Maybe it is not worth putting effort into documentation.

@sone If you could take a look at the changes and give us feedback. It is helpful to have another person review and point out things that need clarification.

**Comment by jln-** [comment]
Yes, so far I only dealt with vbap documentation. I'll make one for the define_loudspeakers object, if only to state that its functions are now implemented in vbap.

Not sure what is happening with the JSUI or panel not working (they do work fine here Max 7.3.4 64bit). We have to investigate this.

I also think about removing the simple GUI tab from vbap help patch and make a proper real-life use example patch. Not sure yet. Just an idea

**Comment by sone** [comment]
The new documentation looks very good! Below you find a first fast feedback. I looked into version 1.0.3 (03/06) for reference. I just wrote down "everything" so eventually some of the feedback is not of value...

---
- Regarding your discussion about define_loudspeakers: 
It's is for changing many vbap objets the same time - at least this is written in the 1.0.3 help patch. The messages to this object are different: ls-triplets and ls-directions. ls-triplets is marked as for experts only and it's about defining a different triangle selection for 3D setups.

_Main help patch:_

- The 4 values are not updated if a value is changing because there is no bang to the leftmost inlet following the number. 

- There are no boxes connected to the outlets - with these you can see e.g. what happens if the azimuth is over 180 or below -180.

- Here we have floats - in the version 1.0.3 we have integers for azi, ele and spread and a float for general/source gain. 
- In the old help-patch the range for spread is limited to 0-100 and gain-range is limited to 0.-2.. 

- It would make sense to have a dac~-toggle and a gain default of 0.

- Below the header it's written "Ville Pulkki 1999-2003 / 2015 update by Nathan Wolek" - isn't it updated 2017?

_Simple GUI:_ 

- Six speaker setup - speakers 5 and 6 are drawn with a big dark-grey circle around the small blue one. 
- If the cursor/sound source moves out of the speaker-circle the spread parameter gets negativ.

---

BTW: Why the file "package-info.json.in" has an ".in" post-fix?

Cheers

**Comment by jln-** [comment]
Hi @sone Thanks for your feedbacks !

Regarding [define_loudspeakers] at first sight, I am not sure about what is written in the old maxhelp. AFAIK all of this object messages are now embedded in vbap so I'm not sure it offers functions vbap doesn't. I have to check though and make proper doc anyway.

> The 4 values are not updated if a value is changing because there is no bang to the leftmost inlet following the number.

Yes, I wasn't sure doing it as I did was a good idea. I wanted to keep it clean but your comment confirms me it is not a good idea. This is fixed so it works right out of the box.

> Here we have floats - in the version 1.0.3 we have integers for azi, ele and spread and a float for general/source gain.

The updates Nathan did in 2015 (IIRC) was adding supports for floats. 

I also agree with other comments or feedbacks. I updated or enhanced maxhelp accordingly. I also added a simple demo patch.

**Comment by sone** [comment]
hi  @jln- - you're right about [define_loudspeakers] because in the vbap source there is:
"#include "../define_loudspeakers/define_loudspeakers.cpp" - sorry, I havent't looked at the source before - now it's also clear to me it is about floats today and not integers anymore... 
But maybe it's a good idea to document the advanced functionality to change triangles for special 3D setups if it is working with message "ls-triplets". 

Have you seen the old help-patch where there is a sub-patcher between matrix~ and dac~ with delays for each channel to compensate loudspeaker-setups with different/irregular distances? It's not "core-vbap" but maybe nevertheless a good idea/thing to include.

**Comment by nwolek** [comment]
Thanks for the feedback, @sone! I have two quick comments, but will write more later:

* floats - Support for these was added during my 2015 update.
* year/credits - Yes, some work was done in 2015, but we should add 2017 too. I think we should add @jln- here too for the documentation work.

**Comment by nwolek** [comment]
@jln- @sone 
I am having trouble sorting out the different issues in this exchange. I am going to parse as many as possible into new separate issues. If you see that I overlooked something, please feel free to open a new issue.
